##  Programming Assignment_13_solution


### 1. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 C D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [11]:
import math

In [13]:
# D=100,150,180
C = 50
H = 30

val = input("Enter values:")
value = []

items=[x for x in val.split(',')]
for D in items:
    value.append(str(int(round(math.sqrt(2*C*float(D)/H)))))

print('Output is',','.join(value))

Enter values:100,150,180
Output is 18,22,24


### 2. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

In [14]:
row = int(input("Input number of rows: "))
col = int(input("Input number of columns: "))
arr = [[0 for j in range(col)] for i in range(row)]

for i in range(row):
    for j in range(col):
        arr[i][j]= i*j

print("2d array is",arr)

Input number of rows: 3
Input number of columns: 3
2d array is [[0, 0, 0], [0, 1, 2], [0, 2, 4]]


In [20]:
import numpy as np
arr=np.array(arr)
print(arr)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.shape

(3, 3)

In [29]:
#dir(arr)

### 3. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

In [30]:
sequence = input("comma separated sequence of words:")
words = [word for word in sequence.split(',')]
print(words)

comma separated sequence of words:boll,doll,maggi,moon,papaya,lion
['boll', 'doll', 'maggi', 'moon', 'papaya', 'lion']


In [31]:
#sorted by set() method
set(words)

{'boll', 'doll', 'lion', 'maggi', 'moon', 'papaya'}

In [32]:
list(set(words))

['papaya', 'doll', 'moon', 'boll', 'maggi', 'lion']

In [33]:
# sorted into list
sorted(list(set(words)))

['boll', 'doll', 'lion', 'maggi', 'moon', 'papaya']

### 4. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [34]:
sequence = input("whitespace separated sequence of words:")
words = [word for word in sequence.split(' ')]
print(words)

whitespace separated sequence of words:moon gun pen pen book book mango apple emli
['moon', 'gun', 'pen', 'pen', 'book', 'book', 'mango', 'apple', 'emli']


In [35]:
#sorted by set() method
set(words)

{'apple', 'book', 'emli', 'gun', 'mango', 'moon', 'pen'}

In [36]:
list(set(words))

['apple', 'mango', 'book', 'moon', 'pen', 'gun', 'emli']

In [37]:
# sorted into list
sorted(list(set(words)))

['apple', 'book', 'emli', 'gun', 'mango', 'moon', 'pen']

### 5. Write a program that accepts a sentence and calculate the number of letters and digits.

In [41]:
# by isalpha() method

str1 = input('Enter a string with number:')
count = 0                   # for count of letters

for i in str1:
    if (i.isalpha()):
        count = count+1
        
print('Count of digits:', len(str1)-count)
print('Count of letters:', count)

Enter a string with number:follow2dream5
Count of digits: 2
Count of letters: 11


### 6. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

In [42]:
import re


In [44]:
pw = input("Enter a password: ")
pw = pw.split(",")

accepted_pass = []
for i in pw:
    
    if len(i) < 6 or len(i) > 12:
        continue

    elif not re.search("([a-z])+", i):
        continue

    elif not re.search("([A-Z])+", i):
        continue

    elif not re.search("([0-9])+", i):
        continue

    elif not re.search("([!@$%^&])+", i):
        continue

    else:
        accepted_pass.append(i)

print('Password is',accepted_pass)

Enter a password: jhuL90000^
Password is ['jhuL90000^']


In [45]:
pw = input("Enter passwords :")
list1 = pw.split(",")
for i in list1:
    if(len(i)>=6 and len(i)<=12):
        if re.search("([a-z])+", i):
            if re.search("([A-Z])+", i):
                if re.search("([0-9])+", i):
                    if re.search("([#,@,$])+", i):
                        print('password is', i)

Enter passwords :SE443e$$
password is SE443e$$
