# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [1]:
#import numpy
import numpy as np

In [2]:
a=[[1,2,3],[4,3,2],[2,3,3]]
b=[[1,2,4],[7,6,5],[2,0,3]]

print(a)
print(b)


[[1, 2, 3], [4, 3, 2], [2, 3, 3]]
[[1, 2, 4], [7, 6, 5], [2, 0, 3]]


In [3]:
A=np.array(a)
B=np.array(b)
print( 'Mat A:') 
print(A)
print('mat B:')
print(B)


Mat A:
[[1 2 3]
 [4 3 2]
 [2 3 3]]
mat B:
[[1 2 4]
 [7 6 5]
 [2 0 3]]


In [4]:
print('Addition of mat:C \n', A+B)

Addition of mat:C 
 [[ 2  4  7]
 [11  9  7]
 [ 4  3  6]]


In [5]:
#or
#for addition 
C = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(A)):  #iteration of rows
    for j in range(len(A[0])): ##iteration of columns
        C[i][j] = A[i][j] + B[i][j]
for k in C:
    print(k)
print('Addition of two mat:',C)

[2, 4, 7]
[11, 9, 7]
[4, 3, 6]
Addition of two mat: [[2, 4, 7], [11, 9, 7], [4, 3, 6]]


### 2. Write a Python Program to Multiply Two Matrices?

In [6]:
A=np.array(a)
B=np.array(b)
print( 'Mat A:') 
print(A)
print('mat B:')
print(B)


Mat A:
[[1 2 3]
 [4 3 2]
 [2 3 3]]
mat B:
[[1 2 4]
 [7 6 5]
 [2 0 3]]


In [7]:
#Multiplication of matrics:
print('Multiplication of mat: \n',A*B)

Multiplication of mat: 
 [[ 1  4 12]
 [28 18 10]
 [ 4  0  9]]


### 3. Write a Python Program to Transpose a Matrix?

In [8]:
a=[[1,2,3],[4,5,6],[8,8,9]]
a

[[1, 2, 3], [4, 5, 6], [8, 8, 9]]

In [9]:
import numpy as np
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [10]:
#transpose of matrix
b.transpose()

array([[1, 4, 8],
       [2, 5, 8],
       [3, 6, 9]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [11]:
# using sort() method
list1  = ['Payal','Minal','Heena','Achal']
list1

['Payal', 'Minal', 'Heena', 'Achal']

In [12]:
list1.sort()


In [13]:
print(list1)

['Achal', 'Heena', 'Minal', 'Payal']


### 5. Write a Python Program to Remove Punctuation From a String?

In [14]:
import string

In [15]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
#string with Punctuation
str1 = 'Python< is! a@ programming# &language'
str1

'Python< is! a@ programming# &language'

In [17]:
#to remove Punctuation
for c in string.punctuation:
    str1 = str1.replace(c,"")

In [18]:
print(str1)

Python is a programming language
